version: '3'
services: 
        web: 
           image: my-static-website
           build: .
           container_name: website
           restart: always
           ports: 
             - "8080:80"
